class FoodEntry {
  final String id; // Firestore doc id
  final DateTime timestamp; // precise time added
  final String day; // YYYY-MM-DD for querying
  final String name;
  final String mealType; // breakfast, lunch, dinner, snack
  final double calories;
  final double protein;
  final double carbs;
  final double fat;
  final bool aiSuggested; // true if generated by AI planner
  final String? source; // optional source info (e.g. model or dataset)

  const FoodEntry({
    required this.id,
    required this.timestamp,
    required this.day,
    required this.name,
    required this.mealType,
    required this.calories,
    required this.protein,
    required this.carbs,
    required this.fat,
    this.aiSuggested = false,
    this.source,
  });

  Map<String, dynamic> toMap() => {
    'timestamp': timestamp.toIso8601String(),
    'day': day,
    'name': name,
    'mealType': mealType,
    'calories': calories,
    'protein': protein,
    'carbs': carbs,
    'fat': fat,
    'aiSuggested': aiSuggested,
    'source': source,
  };

  static FoodEntry fromMap(String id, Map<String, dynamic> map) => FoodEntry(
    id: id,
    timestamp:
        DateTime.tryParse(map['timestamp'] as String? ?? '') ?? DateTime.now(),
    day: map['day'] as String? ?? _fmtDay(DateTime.now()),
    name: map['name'] as String? ?? 'Unknown',
    mealType: map['mealType'] as String? ?? 'other',
    calories: (map['calories'] as num?)?.toDouble() ?? 0,
    protein: (map['protein'] as num?)?.toDouble() ?? 0,
    carbs: (map['carbs'] as num?)?.toDouble() ?? 0,
    fat: (map['fat'] as num?)?.toDouble() ?? 0,
    aiSuggested: (map['aiSuggested'] as bool?) ?? false,
    source: map['source'] as String?,
  );

  FoodEntry copyWith({
    String? id,
    DateTime? timestamp,
    String? day,
    String? name,
    String? mealType,
    double? calories,
    double? protein,
    double? carbs,
    double? fat,
    bool? aiSuggested,
    String? source,
  }) => FoodEntry(
    id: id ?? this.id,
    timestamp: timestamp ?? this.timestamp,
    day: day ?? this.day,
    name: name ?? this.name,
    mealType: mealType ?? this.mealType,
    calories: calories ?? this.calories,
    protein: protein ?? this.protein,
    carbs: carbs ?? this.carbs,
    fat: fat ?? this.fat,
    aiSuggested: aiSuggested ?? this.aiSuggested,
    source: source ?? this.source,
  );

  static String _fmtDay(DateTime dt) =>
      '${dt.year.toString().padLeft(4, '0')}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')}';

  static String formatDay(DateTime dt) => _fmtDay(dt);
}
