// Placeholder generated by tool to allow compilation until FlutterFire CLI generates real options.
// Run: flutterfire configure --project=se-305-db --out=lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
      'DefaultFirebaseOptions not generated. Run flutterfire configure to create lib/firebase_options.dart.',
    );
  }
}
